name: treestride
description: "Application for fitness and environmental conservation."
publish_to: "none"
version: 1.0.1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cached_network_image: ^3.4.0
  cloud_firestore: ^5.0.0
  connectivity_plus: ^6.0.3
  crypto: ^3.0.3
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_storage: ^12.0.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.2.1+2
  flutter_map: ^7.0.2
  fluttertoast: ^8.2.6
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  image: ^4.2.0
  image_cropper: ^8.0.1
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  latlong2: ^0.9.1
  open_mail_app: ^0.4.5
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  scan: ^1.6.0
  screenshot: ^3.0.0
  sensors_plus: ^5.0.1
  share_plus: ^9.0.0
  shared_preferences: ^2.3.1
  url_launcher: ^6.3.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

flutter_icons:
  android: true
  image_path: "assets/images/icon.png"
