// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUIljfabkgsGO8FkLTfSNMpd7NeZW0a_M',
    appId: '1:218404996569:web:de3f621f5c9f849ee5c5c8',
    messagingSenderId: '218404996569',
    projectId: 'treestride-project',
    authDomain: 'treestride-project.firebaseapp.com',
    storageBucket: 'treestride-project.appspot.com',
    measurementId: 'G-0GFGWJ0ML2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSP934kG7bBgpcLlJffCD9pO_9wznwBpM',
    appId: '1:218404996569:android:8f1556da0bedfe17e5c5c8',
    messagingSenderId: '218404996569',
    projectId: 'treestride-project',
    storageBucket: 'treestride-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnUZRRvudmuhAzEvV6yCdZaqZc6K2cGAs',
    appId: '1:218404996569:ios:0cdfe8e2ab22ec68e5c5c8',
    messagingSenderId: '218404996569',
    projectId: 'treestride-project',
    storageBucket: 'treestride-project.appspot.com',
    iosBundleId: 'com.example.treestride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnUZRRvudmuhAzEvV6yCdZaqZc6K2cGAs',
    appId: '1:218404996569:ios:0cdfe8e2ab22ec68e5c5c8',
    messagingSenderId: '218404996569',
    projectId: 'treestride-project',
    storageBucket: 'treestride-project.appspot.com',
    iosBundleId: 'com.example.treestride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUIljfabkgsGO8FkLTfSNMpd7NeZW0a_M',
    appId: '1:218404996569:web:3016860bdec6cce1e5c5c8',
    messagingSenderId: '218404996569',
    projectId: 'treestride-project',
    authDomain: 'treestride-project.firebaseapp.com',
    storageBucket: 'treestride-project.appspot.com',
    measurementId: 'G-156M1CGQLZ',
  );
}
